### ISSUE TITLE
Getting access denied error

### ISSUE THREAD

**Issue by Sannidhya127** [seddie95/python_script_in_right_click_menu#4]
getting this error: 
 key = reg.CreateKey(reg.HKEY_CLASSES_ROOT, key_path)
PermissionError: [WinError 5] Access is denied

**Comment by seddie95** [comment]
this may be caused by not having administrator access when you run the script , make sure to open  your ide as administrator

**Comment by Sannidhya127** [comment]
> this may be caused by not having administrator access when you run the script , make sure to open your ide as administrator

Thanks! It worked!

**Comment by seddie95** [comment]
No worries glad to help
